#' enumerate XML attributes for GENESET entities in MSigDb
#' @examples
#' head(all_attrs())
#' @export
all_attrs = function() c("STANDARD_NAME", "SYSTEMATIC_NAME", "HISTORICAL_NAMES", "ORGANISM", 
"PMID", "AUTHORS", "GEOID", "EXACT_SOURCE", "GENESET_LISTING_URL", 
"EXTERNAL_DETAILS_URL", "CHIP", "CATEGORY_CODE", "SUB_CATEGORY_CODE", 
"CONTRIBUTOR", "CONTRIBUTOR_ORG", "DESCRIPTION_BRIEF", "DESCRIPTION_FULL", 
"TAGS", "MEMBERS", "MEMBERS_SYMBOLIZED", "MEMBERS_EZID", "MEMBERS_MAPPING", 
"FOUNDER_NAMES", "REFINEMENT_DATASETS", "VALIDATION_DATASETS"
)

